name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:


  build-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file
      run: echo "${{ secrets.MAIN_ENV }}" > ./.env

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Project Docker image
      run: |
        docker build -t toxicblade/project-name:project ./
        docker push toxicblade/project-name:project

  Release:
    runs-on: ubuntu-latest
    needs: [ build-project]
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.PAT_TOKEN }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        generateReleaseNotes: true
